name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"

      - name: Run DBM Checks
        uses: DeadlyBossMods/DBM-Actions@master

      - name: Create Package
        uses: BigWigsMods/packager@master
        if: ${{ github.event_name != 'pull_request' }}
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

      - name: Send Status to Discord
        uses: nebularg/actions-discord-webhook@v1
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
        if: ${{ github.event_name != 'pull_request' && failure() }}
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    needs:
      - build

    steps:
      - uses: actions/checkout@v1
        with:
          repository: 'DeadlyBossMods/DBM-WoTLKC'
          ref: 'master'
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Deploy on DBM-WoTLKC
        run: |
          COMMIT_MESSAGE=$(cat <<'EOF'
          ${{ github.event.head_commit.message }}
          EOF
          )
          COMMIT_MESSAGE=$(echo $COMMIT_MESSAGE | sed 's/"/\\"/g')
          cd /home/runner/work/DBM-WotLK/DBM-WoTLKC
          git remote set-url origin "https://${{ secrets.PERSONAL_TOKEN }}@github.com/DeadlyBossMods/DBM-WoTLKC.git"
          git config user.email "${{ github.event.head_commit.author.email }}"
          git config user.name "${{ github.event.head_commit.author.username }}"
          git commit --allow-empty -m "$COMMIT_MESSAGE"
          git push origin HEAD:master
